package compiler;

import parser.Recognizer;

import java.io.PrintWriter;

public class CompilerMain
{
    public static void main(String[] args)
    {

        if (args.length == 0)
        {
            System.out.println("Please enter a file name");
            System.exit(0); //or return? exit runs faster.
        }
        else
        {
            /*Takes an input file from the command line argument and
            stores it in a String called fileName.*/
            String fileName = args[0];
            Recognizer instance = new Recognizer
                    (fileName, true);
            /*Calls Recognizer Object method program. Constructor
            is automatically called when an object of the class is
            created. */
            instance.program();
            /*The symbol table toString generated by passing the file
            into the program method. */
            String tableString = instance.getSymbolTable().toString();
           
        }
    }
}
